apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-bonus1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-bonus1
  template:
    metadata:
      labels:
        app: api-bonus1
    spec:
      containers:
        - name: api-bonus1
          image: rodolfohok/api-bootcamp-produto:v2
          resources:
            requests:
              cpu: "100m"
              memory: "32Mi"
            limits:
              cpu: "200m"
              memory: "64Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 0
            timeoutSeconds: 5
            failureThreshold: 1
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /read
              port: 8080
            initialDelaySeconds: 0
            timeoutSeconds: 5
            failureThreshold: 1
            successThreshold: 1
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_URI
              value: mongodb://mongouser:mongopwd@mongodb-service:27017/admin

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoScaler
metadata:
  name: api-bonus1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-bonus1
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

---

apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
  type: NodePort